id: 0249916bfad94d48b9dbe070675756e9
initial_creation_type: ocr
source_metadata:
  volumes:
    fc3a7aef5c734e62acda7bebd6397542:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: སེམས་ཀྱི་རྡོ་རྗེའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
